### ISSUE TITLE
[Enhancement]: Fix incorrect link on Data Feeds docs page

### ISSUE THREAD

**Issue by bitwhispererrr** [smartcontractkit/documentation#1022]
### What would you like us to improve?
On page: (https://docs.chain.link/docs/data-feeds/)
Link to Data Feed Contract Addresses page pointing to  (/docs/data-feeds/price-feeds/) instead of  (/docs/data-feeds/price-feeds/addresses/)

### How important it is?

Just a typo in the docs , might cause users to jump back and forth between pages before figuring out it's the wrong link :)

**Comment by Rahul-Prasad-07** [comment]
this issue is already fixed, It's good to close it ?

**Comment by dwightjl** [comment]
This is fixed.
