### ISSUE TITLE
404: get random number example

### ISSUE THREAD

**Issue by roomforyeesus** [smartcontractkit/documentation#1025]
### Describe the bug

404 on the https://docs.chain.link/docs/vrf/v2/examples/get-a-random-number/ page

### To Reproduce

go to 
https://docs.chain.link/docs/vrf/v2/examples/get-a-random-number/

### URLs

[- https://docs.chain.link/..
- ...](https://docs.chain.link/docs/vrf/v2/examples/get-a-random-number/)

### Expected behavior

some sort of tutorial on api calls

**Comment by aelmanaa** [comment]
Hi there,

thanks for reaching out. I'm going to add few redirects but please note that the correct links are :

- [Get a random number](https://docs.chain.link/docs/vrf/v2/subscription/examples/get-a-random-number/) with the [Subscription Method](https://docs.chain.link/docs/vrf/v2/subscription/)
- [Get a random number](https://docs.chain.link/docs/vrf/v2/direct-funding/) with the [Direct Funding Method](https://docs.chain.link/docs/vrf/v2/direct-funding/)
