### ISSUE TITLE
[Enhancement]:Add 'merge' task to Job > Tasks documentation

### ISSUE THREAD

**Issue by zeuslawyer** [smartcontractkit/documentation#1033]
### What would you like us to improve?

There appears to be a `merge` task that is possible (see [this issue on the chainlink repo](https://github.com/smartcontractkit/chainlink/issues/7695))

We have no documentation on this.  Appears to be that the issue author used the [source code](https://github.com/smartcontractkit/chainlink/blob/5a830b237cd187eaf9bb5735d8610835520a82c3/core/services/pipeline/task.merge.go) to understand this task.

I was able to get help from Andrei S to troubleshoot the original issue, but documenting the Merge task is probably the right way to go.

### How important it is?

In general, I always view documentation as top priority, but given this may be obscure and not known widely, i will leave the prioritization to you!  I'd say 6/10. :)

**Comment by dwightjl** [comment]
Fixed by https://github.com/smartcontractkit/documentation/pull/1284
