### ISSUE TITLE
Removed "intermediates" and "advanced" tutorials name

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#104]
## Intuition
1. "intermediates" isn't a word

We can just have in the "api call" tutorial that the randomness one is a prerequisite. 

https://docs.chain.link/docs/intermediates-tutorial/

**Comment by dmitrydao** [comment]
We can have `intermediate` which is a word : )

**Comment by dmitrydao** [comment]
@PatrickAlphaC Let me know your thoughts on this. If we make generic names like Price Feeds, API Calls and Random Numbers, then what is the difference between documents with the corresponding products?

**Comment by PatrickAlphaC** [comment]
<img width="255" alt="Screen Shot 2021-06-03 at 11 31 14 AM" src="https://user-images.githubusercontent.com/54278053/120671261-367c8700-c45f-11eb-80db-9fc72c2e8722.png">
Let's just change this to:
Beginners
Random Numbers
API Calls
