### ISSUE TITLE
[Enhancement]: Remove empty faucet from `_src/reference/chains.json`

### ISSUE THREAD

**Issue by alex-pakalniskis** [smartcontractkit/documentation#1044]
### What would you like us to improve?

One of the listed Faucets in `_src/reference/chains.json` is empty: https://goerli-faucet.mudit.blog/

This same faucet is recommended by another Chainlink page: https://faucets.chain.link/

I think this faucet should be removed from list of faucets recommended to the community.

### How important it is?

Not super important but could help users looking for an active faucet.

**Comment by aelmanaa** [comment]
Hi @alex-pakalniskis 

thanks for flagging this. Just opened this issue https://github.com/ethereum-lists/chains/issues/1884 as `chains.json` uses https://chainid.network/chains.json as reference

**Comment by dwightjl** [comment]
The drained faucet is removed. Currently it looks like the following faucets are listed:

"http://fauceth.komputing.org?chain=5&address=${ADDRESS}",
"https://goerli-faucet.slock.it?address=${ADDRESS}",
"https://faucet.goerli.mudit.blog"
