### ISSUE TITLE
[Bug]: <remove ROOT variable from .env file>

### ISSUE THREAD

**Issue by hakkisabah** [smartcontractkit/documentation#1073]
### Describe the bug

For version 1.10.0 : 

While docker initialize container, getting create error and we understand after looking the https://docs.chain.link/chainlink-nodes/configuration-variables/#root link we dont need this because parameter has configured as default anyway.

Its tried and no problem.

### To Reproduce

1. Go to ~/.chainlink-goerli and ~/.chainlink location
2. find ROOT line both .env files
3. See error while starting node with docker

### URLs

- [in requirements](https://docs.chain.link/chainlink-nodes/running-a-chainlink-node#requirements-1). 
- [configuration reference](https://docs.chain.link/chainlink-nodes/configuration-variables/#root).

### Expected behavior

Explained in describe the bug section

**Comment by dwightjl** [comment]
Root ENV has been removed from the example config. All of our examples use the default now.
https://github.com/smartcontractkit/documentation/pull/1108
