### ISSUE TITLE
[Bug]: Edit button does not link properly to index.md files

### ISSUE THREAD

**Issue by dwightjl** [smartcontractkit/documentation#1149]
### Describe the bug

https://docs.chain.link/data-feeds

The "Edit this page" button links to here: https://github.com/smartcontractkit/documentation/tree/main/src/pages/data-feeds.md

The actual file is here:
https://github.com/smartcontractkit/documentation/blob/main/src/pages/data-feeds/index.mdx

### To Reproduce

Use the edit this page button here: https://docs.chain.link/data-feeds

### URLs

[- https://docs.chain.link/..
- ...
](https://docs.chain.link/data-feeds)

### Expected behavior

Opening the correct file on GitHub

**Comment by thedriftofwords** [comment]
https://github.com/smartcontractkit/documentation/blob/main/src/layouts/MainLayout.astro#L16-L18 <-- Where the GitHub edit URL is set. Either we add some custom logic to handle the index files or see if there's something in Astro that provides the filename as a variable.
