### ISSUE TITLE
[Enhancement]: <Page Not Found - GitHub 404>

### ISSUE THREAD

**Issue by alymurtazamemon** [smartcontractkit/documentation#1161]
### What would you like us to improve?

[Historical Price Data](https://docs.chain.link/data-feeds/price-feeds/historical-data) page's **Edit this page** option shows the Page Not Found - GitHub 404 error. Its link needs to be updated.

### How important it is?

This will be helpful for contributors to find the Historical Price Data page documentation from the same page and help them to fix issues or typos mistakes.

**Comment by dwightjl** [comment]
Thank you! The edit button wasn't identifying .mdx and index files correctly. This is fixed now.
