### ISSUE TITLE
[Enhancement]: Explain how to use the output from Mode Task

### ISSUE THREAD

**Issue by marcelofrayha** [smartcontractkit/documentation#1234]
### What would you like us to improve?

I had a hard time to figure out how to pass the output from mode task to ethabiencode task, so I think it would be important to explain how it is done.

I suggest adding the following information to the docs regarding mode task (https://docs.chain.link/chainlink-nodes/oracle-jobs/task-types/task_mode):

**Using the Output**

To pass the results array to ethabiencode task you must specify in the ABI that the data is an array and point the data parameter to "YOUR_MODE_TASK.results" like this:

```toml
encode_mode_task [type="ethabiencode" abi="(bytes32 requestId, uint256[] _data)" data="{\\"requestId\\": $(decode_log.requestId), \\"_data\\": $(YOUR_MODE_TASK.results)}"]
```

### How important it is?

I believe it is fundamental to use mode task. As this task is not very common I couldn't find these instructions anywhere.

**Comment by aelmanaa** [comment]
thanks @marcelofrayha ! we've just made the fix.

**Comment by marcelofrayha** [comment]
Awesome, thanks for the update!

Em sex., 2 de jun. de 2023 às 04:26, Amine E. ***@***.***>
escreveu:
