### ISSUE TITLE
[Bug]: wrong references to Mumbai on the Functions Getting Started page

### ISSUE THREAD

**Issue by jkondratowicz** [smartcontractkit/documentation#1272]
### Describe the bug

On this page:
https://docs.chain.link/chainlink-functions/getting-started

- The `network` parameter uses an incorrect value (`mumbai` instead of `polygonMumbai`)
- RPC URL env variable has a different name than expected by Hardhat

So following the instructions on the page gets you "Error HH100: Network mumbai doesn't exist" or bad URL error.

### To Reproduce

1. Follow instructions on this page: https://docs.chain.link/chainlink-functions/getting-started

### URLs

- https://docs.chain.link/chainlink-functions/getting-started

**Comment by aelmanaa** [comment]
HI @jkondratowicz 

tahnks a lot and sorry for that. should be solved
