### ISSUE TITLE
Add Heartbeat and Deviation to Contract Pages

### ISSUE THREAD

**Issue by SeaAnenome** [smartcontractkit/documentation#129]
data.chain.link is a very inefficient way for a customer to see heartbeat and deviation thresholds for feeds, and some feeds are not visualized on that page. As such, there is no way for a user to find this information in some cases, or in the best case scenario, it will take them a while to obtain the information. 

I propose adding a column for deviation and a column for heartbeat on these pages, just like we have for decimals. 

https://docs.chain.link/docs/ethereum-addresses/
https://docs.chain.link/docs/binance-smart-chain-addresses/
https://docs.chain.link/docs/matic-addresses/
https://docs.chain.link/docs/xdai-price-feeds/
https://docs.chain.link/docs/huobi-eco-chain-price-feeds/
https://docs.chain.link/docs/avalanche-price-feeds/

**Comment by alexroan** [comment]
I agree that this information is currently difficult to find, or impossible without contacting the team in some cases. However, I wonder whether this data fits here, or if it should live somewhere else.

The current fields (decimals and address) directly affect the consumer contract. Both are critical in consuming the data. We know that these pages are used primarily for copy-pasting. If we add heartbeat and deviation, I worry that we're muddying this very targeted water with less important info.

That's my gut, open to opposing view though.

**Comment by alexroan** [comment]
See the image below for the suggested approach. I've been informed that this is something that we're frequently asked about, so we should go ahead and do this.

![image (2)](https://user-images.githubusercontent.com/6523673/120823515-6acf7080-c54f-11eb-8d8d-62e15a9434c0.png)

**Comment by dmitrydao** [comment]
fixed with #189
