### ISSUE TITLE
[Bug]: <your-title-here>link to POR broken

### ISSUE THREAD

**Issue by dinesti1** [smartcontractkit/documentation#1303]
### Describe the bug

Unable to find tokenomics doc for LINK

### To Reproduce

1. I searched "tokenomics" on your site
Result: Proof or reserve (BTC)
3. Click on result link
4. See error: 404 page not found

### URLs

- https://docs.chain.link/..
- ...
https://docs.chain.link/chainlink-nodes/proof-of-reserves-btc

### Expected behavior

Looking for your tokenomics and proof of reserves docs

**Comment by dwightjl** [comment]
Our in-documentation search was improved recently, so the results should be more accurate now. The https://docs.chain.link/chainlink-nodes/proof-of-reserves-btc page has been removed for some time and does not appear to be showing up in results anymore. These links should have information related to what you were searching for.

- https://chain.link/economics
- https://docs.chain.link/data-feeds/proof-of-reserve
