### ISSUE TITLE
WeChat: Social Link(Wrong Link) in Footer

### ISSUE THREAD

**Issue by KarthickSakthi** [smartcontractkit/documentation#1312]
### Describe the bug

In the Footer, Social Link Section for WeChat is Wrong

The current Link that added in href was: 
`https://blog.chain.link/chainlink-chinese-communities/?_ga=2.7080626.1865446767.1684655565-2049420124.1668651577`

### To Reproduce

1. Go to 'Footer'
2. Click on '[WeChat](https://blog.chain.link/chainlink-chinese-communities/?_ga=2.7080626.1865446767.1684655565-2049420124.1668651577)' in **Social** Section
3. See it wasn't opened the WeChat, instead it opening a Chain Link Blog

### URLs

- https://docs.chain.link/..
- ...

### Expected behavior

It should Move to The ChainLink account or Page in WeChat

**Comment by KarthickSakthi** [comment]
I am interested work on this issue, Kindly Give me the url of ChainLink's We chat Account. I'LL give a PR
Thanks in advance

**Comment by aelmanaa** [comment]
Hello @KarthickSakthi 

First of all, thank you very much for your contribution. The link opens a blog that contains 2 QR wechat codes 

![image](https://github.com/smartcontractkit/documentation/assets/4503543/7f6bd686-e131-464d-9004-1532e795a4a5)

If you are looking to contribute to other issues. Happy to help you fix other issues

**Comment by KarthickSakthi** [comment]
Thank you @aelmanaa
