### ISSUE TITLE
[Enhancement]: Remove file from .prettierignore

### ISSUE THREAD

**Issue by simkasss** [smartcontractkit/documentation#1377]
### What would you like us to improve?

The file "chainlink-nodes/v1/running-a-chainlink-node.mdx" is included in the .prettierignore file.
If this path is not added to .prettierignore, Prettier formats the file incorrectly, causing the page to break.
Need to find a solution to this problem without adding the file to .prettierignore.

### How important it is?

Arbitrarily adding files to .prettierignore is a bad practice.

**Comment by aelmanaa** [comment]
thanks @simkasss! Please take a look at the linked PR
