### ISSUE TITLE
[Bug]: CCIP Transfer Tokens with Data mixup

### ISSUE THREAD

**Issue by codetributor** [smartcontractkit/documentation#1410]
### Describe the bug

mix up between Ethereum Sepolia and Polygon Mumbai

### To Reproduce

1. Go to CCIP docs
2. then go the Transfer Token with Data tutorial
3. then go the step 4. Deploy your receiver contract on Polygon Mumbai:
4. then go to step 6. Enable your contract to receive CCIP messages from the contract that you deployed on Ethereum Sepolia:
5. see error step 1. In Remix IDE, under Deploy & Run Transactions, open the list of transactions of your smart contract deployed on Ethereum Sepolia.

I think it should be Polygon Mumbai.

### URLs

https://docs.chain.link/ccip/tutorials/programmable-token-transfers

### Additional context

let me know if you want me to submit a pull request

**Comment by codetributor** [comment]
I think its the same for step 5. Enable your contract to receive CCIP messages from Ethereum Sepolia:
see error step 1. In Remix IDE, under Deploy & Run Transactions, open the list of transactions of your smart contract deployed on Ethereum Sepolia.

I think it should be Polygon Mumbai

**Comment by aelmanaa** [comment]
Hi @codetributor 

Good catch! Thank you very much. I see we made the same mistake in the [Send Arbitrary Data tutorial](https://docs.chain.link/ccip/tutorials/send-arbitrary-data).
Yes, please submit a PR, and I'll merge it. Can we do it within the next 24h?

**Comment by codetributor** [comment]
Yeee !! okay I'll do it right now. Give me this afternoon to look into the Send Arbitrary Data tutorial also.

**Comment by aelmanaa** [comment]
Thank you @codetributor !
