### ISSUE TITLE
[Enhancement]: <your-title-here>

### ISSUE THREAD

**Issue by skywalker2017** [smartcontractkit/documentation#1468]
### What would you like us to improve?

<img width="868" alt="image" src="https://github.com/smartcontractkit/documentation/assets/19268240/1a1bd419-7af5-4ea1-9a11-fd63441a6197">

spelling fix

### How important it is?

not important

**Comment by aelmanaa** [comment]
@skywalker2017, what's the spelling issue? Looks correct to me 

unidirectional: involving, functioning, moving, or responsive in a single direction  (cf. [definition](https://www.merriam-webster.com/dictionary/unidirectional))

**Comment by aelmanaa** [comment]
Closing it for now but feel free to re-open it in case I'm missing anything.
