### ISSUE TITLE
Mention the chainlink github has instructions for running from source

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#157]
https://docs.chain.link/docs/running-a-chainlink-node/

https://github.com/smartcontractkit/chainlink#install

**Comment by dmitrydao** [comment]
Wait, is it running a CL node or running a CL network from source? I see the instructions for latter.

**Comment by PatrickAlphaC** [comment]
Yes, we should just mention in the docs that if a user wants to run a node from source, they can go to the github readme.
