### ISSUE TITLE
[Enhancement]: How much will it cost to run Functions?!

### ISSUE THREAD

**Issue by kopeboy** [smartcontractkit/documentation#1759]
### What would you like us to improve?

What's the expected cost of running Functions, ie. fetching web2 data from an API and sending it to 1 contract on 1 chain?
How many LINK? Is there a market for that? Is there a minimum DON operators will accept? How does it work? 
I couldn't find anything in the documentation about this.

Also, it takes at least 5 transactions (with fees of each network) just to activate 1 function:
- Terms of service (not a feeless sign but interacting with a contract with subscription billing - misleading to call this ToS)
- Create the subscription,
- Fund it with LINK
- Add a Consumer contract
- Cancel the subscription.

Couldn't you do this in 1 or 2 transactions?!

### How important it is?

Very important for any business to be able to estimate costs 😅

**Comment by aelmanaa** [comment]
Hi @kopeboy 

Thank you for reaching out!

> What's the expected cost of running Functions, ie. fetching web2 data from an API and sending it to 1 contract on 1 chain?
How many LINK?

The [billing page](https://docs.chain.link/chainlink-functions/resources/billing) explains how the cost is calculated. What we will do is add an example for extra clarification. 
Also, note that you can estimate the costs for your function using the [Functions toolkit (SDK)](https://github.com/smartcontractkit/functions-toolkit?tab=readme-ov-file#estimating-request-costs). Each one of the docs' guides shows you how to do so. For instance, the [simple computation ](https://docs.chain.link/chainlink-functions/tutorials/simple-computation): See [here](https://github.com/smartcontractkit/smart-contract-examples/blob/aa6a566f3310a321a1105d8e23669f90c2032eee/functions-examples/examples/1-simple-computation/request.js#L93). 

> Is there a market for that? Is there a minimum DON operators will accept? How does it work?

Can you please elaborate? I didn't understand your question.


> Also, it takes at least 5 transactions (with fees of each network) just to activate 1 function:
> Terms of service (not a feeless sign but interacting with a contract with subscription billing - misleading to call this ToS)
Create the subscription,
Fund it with LINK
Add a Consumer contract
Cancel the subscription.
Couldn't you do this in 1 or 2 transactions?!

Note that Chainlink Functions is still in Beta. This is a valuable feedback that I've just raised with the product team. Thank you for that!

**Comment by aelmanaa** [comment]
Hi @kopeboy 

Is this still an issue?

**Comment by aelmanaa** [comment]
@kopeboy 

we've updated the docs with an [example](https://docs.chain.link/chainlink-functions/resources/billing#cost-calculation-example). 
Closing this issue for now.
