### ISSUE TITLE
[Bug]: Cannot successfully compile Operator.sol

### ISSUE THREAD

**Issue by hyc0812** [smartcontractkit/documentation#1849]
### Describe the bug

Hello, I can't successfully compile the Operator.sol with the link you provide: 

Fulfilling request:
https://docs.chain.link/chainlink-nodes/v1/fulfilling-requests#overview

Set up your Operator contract -> Deploy your own operator contract -> step 1: Go to Remix and open the Operator.sol
Step 2: compile: Can't successfully compile the Operator.sol

### To Reproduce

1. Go to 'https://docs.chain.link/chainlink-nodes/v1/fulfilling-requests#deploy-your-own-operator-contract'
2. Click on 'step 1: Go to Remix and open the Operator.sol'
3. See error in Remix IDE

### URLs

- https://docs.chain.link/chainlink-nodes/v1/fulfilling-requests#deploy-your-own-operator-contract
- ...

**Comment by aelmanaa** [comment]
Hi @hyc0812 

I'm sorry that you are experiencing this issue.  
We are currently working to fix it (cf. this [PR](https://github.com/smartcontractkit/documentation/pull/1854))

Right now, you have two options:

- Use Hardhat or Foundry to compile and deploy the contract. You will not have any issues
- If you want to test locally and prefer to use Remix then as a temporary solution, [open this contract in RemixIDE](https://remix.ethereum.org/#url=https://documentation-git-operator-temp-example-chainlinklabs.vercel.app/samples/ChainlinkNodes/Operator.sol&lang=en&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.19+commit.7dd6d404.js)

**Comment by hyc0812** [comment]
Hi @aelmanaa,

Thank you for providing me with this temporary solution. The second temporary solution is good for me. Thank you for the effort!

**Comment by aelmanaa** [comment]
Closing this for now. Please open it again if you still run into an issue
