### ISSUE TITLE
[Bug]: Wrong Navigation Path

### ISSUE THREAD

**Issue by emmaodia** [smartcontractkit/documentation#2059]
### Describe the bug

The "What's next" section on the page https://docs.chain.link/vrf/v2-5/overview/direct-funding points to v2 links instead of v2.5. 

### To Reproduce

1. Go to https://docs.chain.link/vrf/v2-5/overview/direct-funding
2. Scroll to the "What's next" section at the Bottom of the page.
3. Click on the "Get Random Number" and "Supported Networks"
4. It redirects to v2 pages instead of v2.5

### URLs

https://docs.chain.link/vrf/v2-5/overview/direct-funding

### Expected behavior

The URL paths should connect to v2.5 pages.

**Comment by khadni** [comment]
Thank you very much @emmaodia!
