### ISSUE TITLE
Add Keepers FAQ

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#216]
Getting this question asked a few times. 

1. How often are they updated/call checkupkeep? (Every 20 blocks or so)
2. What's the delay between checkupkeep and perform upkeep? (a few seconds, and perhaps a few blocks depending on the layer 1)
3. Is there a way to verify that performUpkeep is actually run by a Keeper and the data it has passed is legit? (you'd modify your smart contract to only allow responses from those on the registry)
4. Costs

**Comment by dmitrydao** [comment]
https://docs.chain.link/docs/chainlink-keepers/faqs/
