### ISSUE TITLE
"Chainlink contract library" link is broken on the site

### ISSUE THREAD

**Issue by m00ki3** [smartcontractkit/documentation#222]
On this url: https://docs.chain.link/docs/request-and-receive-data/

the "Chainlink contract library" link is broken (404).

**Comment by dmitrydao** [comment]
There's no link that points to the Chainlink contract library. Which one would it be?

**Comment by m00ki3** [comment]
It is. It's in this sentence, in the public/live url I provided. "Whether your contract requires sports results, the latest weather, or any other publicly available data, the Chainlink contract library provides the tools required for your contract to consume it."

**Comment by dmitrydao** [comment]
fixed
