### ISSUE TITLE
<AggregatorV3Interface.sol missing for beginner guide>

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#223]
**Description**
Missing file [AggregatorV3Interface.sol](https://github.com/smartcontractkit/chainlink/blob/master/evm-contracts/src/v0.6/interfaces/AggregatorV3Interface.sol) linked in [Beginner Guide](https://docs.chain.link/docs/beginners-tutorial/#7a-the-remix-ide)

**Your Environment**
Remix - [Sample gist](https://remix.ethereum.org/#version=soljson-v0.6.7+commit.b8d736ae.js&optimize=false&evmVersion=null&gist=0c5928a00094810d2ba01fd8d1083581&runs=200)

**Basic Information**
This is the first piece of code that one tries out when leaning about the basics of chainlink smart contracts development. The code can not be compiled because it is missing the file mentioned above. If new devs can not compile this code they will leave and look for other projects.

**Steps to Reproduce**
try to compile the example in this [Beginner Guide](https://docs.chain.link/docs/beginners-tutorial/)

**Additional Information**
none

**Comment by dmitrydao** [comment]
Thanks for mentioning that. It's because the main path to contracts has changed.
