### ISSUE TITLE
Add LINK token contract peculiarities to https://docs.chain.link/docs/vrf-contracts/

### ISSUE THREAD

**Issue by tkaraivanov** [smartcontractkit/documentation#228]
It would be good to include the following details on https://docs.chain.link/docs/vrf-contracts/

- The callout about the official LINK token on BSC mainnet (+ pegswap). It's currently only included for Polygon
- links to LINK faucets for all testnets

**Comment by dmitrydao** [comment]
Let me know if you can provide such data. I'll definitely include it.

**Comment by tkaraivanov** [comment]
@dmitrydao it's already included in https://docs.chain.link/docs/link-token-contracts/ so it's already available elsewhere in our docs - however some users keep coming to us asking for these details so I thought it would be reasonable to duplicate it here as well.

**Comment by dmitrydao** [comment]
@tkaraivanov I don't like duplicates in general but I opened a PR in any case. @StephenFluin let me know if this is a good approach. I was actually thinking that we move all of our faucets into a js file to dynamically load them where needed.

**Comment by StephenFluin** [comment]
Before we end up duplicating anything in 3 places, we should consider switching to variables/includes from the `_includes` folder. Right now it's in 2 places and could theoretically differ based on the purpose, but it's not ideal.
