### ISSUE TITLE
HECO is not available in https://docs.chain.link/docs/link-token-contracts/

### ISSUE THREAD

**Issue by alexpreukschat** [smartcontractkit/documentation#238]
I am not sure if HECO has no testnet, but in case it does maybe good to add it. The mainnet is also not listed https://docs.chain.link/docs/link-token-contracts/.

**Comment by dmitrydao** [comment]
If HECO is Huobi Eco Chain, then I think this should be it: https://docs.chain.link/docs/reference-contracts/#huobi-eco-chain

**Comment by alexpreukschat** [comment]
Huobi Eco Chain should be here too:
https://docs.chain.link/docs/link-token-contracts/
