### ISSUE TITLE
Chainlink Fulfilling Requests tutoorial is having at discrepancy

### ISSUE THREAD

**Issue by lopeselio** [smartcontractkit/documentation#254]
Inside [the node tutorial](https://docs.chain.link/docs/fulfilling-requests/ )creating TestnetConsumer.sol
![image](https://user-images.githubusercontent.com/43913734/126639212-c624e497-b67b-459e-8bf4-3d3585665b46.png)
The hyperlink links us to the smart contract inside [github gist](https://gist.githubusercontent.com/thodges-gh/8df9420393fb29b216d1832e037f2eff/raw/350addafcd19e984cdd4465921fbcbe7ce8500d4/ATestnetConsumer.sol)
 **_I imported the code to my Remix IDE and it gave an error Ownable.sol can't be found._**

Solution:
The two imports in the gist code need to be updated to the following:
```
import "https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.4/ChainlinkClient.sol";
import "https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.4/vendor/Ownable.sol";
```
the previous links have been modified.

**Comment by dmitrydao** [comment]
Thanks for catching it. There was a recent update of the contracts' path. Try the following imports:
```
import "@chainlink/contracts/src/v0.4/ChainlinkClient.sol";
import "@chainlink/contracts/src/v0.4/vendor/Ownable.sol";
```

**Comment by lopeselio** [comment]
Yeah used this one @dmitrydao . Thanks. Time to update?

**Comment by dmitrydao** [comment]
We're making a mega update soon to avoid any issues with Remix and gists. You're gonna love it so I think it can wait.

**Comment by lopeselio** [comment]
Awesome
