### ISSUE TITLE
Show example of how to send an address in a request

### ISSUE THREAD

**Issue by boxhock** [smartcontractkit/documentation#255]
The API reference here: https://docs.chain.link/docs/chainlink-framework/
Should be updated with an example of passing in an address in the request.

It's currently not clear how to do this. Passing an address as a uint will not work: https://github.com/smartcontractkit/chainlink/issues/4064

Talked to Steve about this, and the recommended way should be something along the lines of:

```javascript
req.addBytes('someAddress', abi.encodePacked(address(this)));
```

We should show this in the docs and make it the recommended way to do this. The only caveat here is that the value received on the CL node/external adapter will be a full word with leading zeroes, encoded with base64.

**Comment by dmitrydao** [comment]
@boxhock can you clarify which example or function you're talking about specifically?

**Comment by boxhock** [comment]
@dmitrydao this would be the documentation for `Chainlink.Request`, and the example should probably be added around the `addBytes()` documentation.

**Comment by boxhock** [comment]
@dmitrydao Also, the `addUint()` section should have a warning that large uints will not get CBOR encoded, and may break the request. This is important.

Talking to Steve to see if we have any solutions to that.

**Comment by dmitrydao** [comment]
@boxhock please check the PR above. It's probably wrong as I still don't fully understand how what you mentioned applies to the function description.

**Comment by boxhock** [comment]
@aelmanaa Can you try this?

Contract:
```solidity
req.addBytes('someAddress', abi.encodePacked(msg.sender));
```

Job spec:
```TOML
observationSource = """
    [...]
    decode [type="ethabidecode"
        abi="bytes someAddress"
        data="$(decode_cbor.someAddress)"]
    [...]
"""
```

The option with using `req.addBytes('address2',abi.encode(msg.sender));` seem to also look pretty good. Don't like the idea of requiring OZ contracts to do this.

What do you prefer between `abi.encode(msg.sender)` and `abi.encodePacked(msg.sender)`?

**Comment by aelmanaa** [comment]
@boxhock thanks! still getting an issue:

```
abi: cannot marshal in to go type: length insufficient 20 require 32

abi: bytes address3

data: $(decode_cbor.address3)
```

this is the json i'm getting after cbor decoding

```json
{"address1":"0x9d087fc03ae39b088326b67fa3c788236645b717","address2":"AAAAAAAAAAAAAAAAnQh/wDrjmwiDJrZ/o8eII2ZFtxc=","address3":"nQh/wDrjmwiDJrZ/o8eII2ZFtxc="}
```

address1 is the string method, address2 the abi.encode and address3 with abi.encoded

I even tried this `abi="bytes20 address3"` but still the same error

**Comment by boxhock** [comment]
@aelmanaa Address3 looks like the best option IMO then, can easily be converted from base64 to hex without the zero padding:

```
> const address2 = Buffer.from('AAAAAAAAAAAAAAAAnQh/wDrjmwiDJrZ/o8eII2ZFtxc=', 'base64')
> address2.toString('hex')
'0000000000000000000000009d087fc03ae39b088326b67fa3c788236645b717'
> const address3 = Buffer.from('nQh/wDrjmwiDJrZ/o8eII2ZFtxc=', 'base64')
> address3.toString('hex')
'9d087fc03ae39b088326b67fa3c788236645b717'
```

As long as you don't need to decode the address inside of the job spec, this should be sufficient.
