### ISSUE TITLE
[FEAT] Dark mode for Chainlink Docs

### ISSUE THREAD

**Issue by JohNostalg** [smartcontractkit/documentation#262]
**Description**
In the Docs we can we add a dark mode option (like a button beside the Github logo to turn Dark mode on/off)

**Motivation**
- Stop Eye Strain
- Don't need to put add-on extensions to webbrowsers to implement Dark Mode
- Doesn't break focus from swapping from VS Code/other code programs to Chainlink docs

**Comment by dwightjl** [comment]
Thank you for the feature request. We have #58 with a simple dark mode work in progress.

Closing this request and merging it with issue #45  which also requests dark mode.
