### ISSUE TITLE
Broken link on market.link

### ISSUE THREAD

**Issue by SeaAnenome** [smartcontractkit/documentation#274]
from: https://market.link/nodes/3e76aa9d-5d04-43fd-8d60-7c01194f3092/integrations?network=56 

Under: 
Steps For Using This Oracle
Write and deploy your Chainlink contract using the network details below
Fund it with LINK
Call your request method

"Write and deploy your Chainlink contract..." hyperlink brings you to a page for interacting with VRF - which seems wrong. 
"Call your request method" is just a straight 404.

**Comment by dmitrydao** [comment]
I think you should bring it up to market.link
Chainlink doesn't run or own this website.
