### ISSUE TITLE
https://docs.chain.link/docs/flightaware-chainlink-testnet#config has been taken down again

### ISSUE THREAD

**Issue by SeaAnenome** [smartcontractkit/documentation#291]
Can we please bring this page back? https://docs.chain.link/docs/flightaware-chainlink-testnet#config

**Comment by dwightjl** [comment]
This seems to be redirecting despite the fact that #303 removes the redirect entry. I'll check this again later to see if I can identify the issue.

**Comment by dwightjl** [comment]
Clearing cache fixes the redirect. The document is restored now.
