### ISSUE TITLE
Consider renaming "Price Feeds" pages

### ISSUE THREAD

**Issue by mccordnate** [smartcontractkit/documentation#295]
There are now more than just price feeds on the price feeds pages. We should consider renaming them to something like "data feeds" to match data.chain.link. Additionally, we should consider separating out price feeds and other types of data feeds.

**Comment by dmitrydao** [comment]
@StephenFluin do you think it makes sense? I think it does.

**Comment by StephenFluin** [comment]
Yes, I chatted about this and got sign off from a bunch of folks. Where appropriate let's rename to the more general `Data Feeds`.

**Comment by dwightjl** [comment]
Dmitry's PR looks good, but we do have other pricing terms to handle. "Historical Price Data" for example.
