### ISSUE TITLE
Missing environment variables

### ISSUE THREAD

**Issue by ArseniiPetrovich** [smartcontractkit/documentation#308]
We have few nodes running on our end. We've been doing some code refactor recently and noticed that there are some env variables in our node that does not exist in the documentation. Here is the full list:
```
MIN_OUTGOING_CONFIRMATIONS
ETH_BALANCE_MONITOR_BLOCK_DELAY
ENABLE_BULLETPROOF_TX_MANAGER
OCR_TRACE_LOGGING
OCR_KEY_BUNDLE_ID
OCR_TRANSMITTER_ADDRESS
```
Can we have the documentation updated to reflect these variables?

P.S. I know, some of these variables are explained in other OCR docs, but it would be great to keep things in the single place.

**Comment by dmitrydao** [comment]
@samsondav can you check these?

**Comment by aelmanaa** [comment]
environment variables listed in https://docs.chain.link/chainlink-nodes/v1/configuration
