### ISSUE TITLE
Link to a page broken

### ISSUE THREAD

**Issue by luigicallero** [smartcontractkit/documentation#318]
In the blog: https://blog.chain.link/build-deploy-and-sell-your-own-dynamic-nft/

there is a broken link named "NFT scavenger hunt" that points to https://docs.chain.link/docs/the-hunt

**Comment by dwightjl** [comment]
This topic was removed here: https://github.com/smartcontractkit/documentation/commit/97fd19c865d640098a425ef83aa185aa5a325fbf

The link is now removed from https://blog.chain.link/build-deploy-and-sell-your-own-dynamic-nft/
