### ISSUE TITLE
TestnetConsumer.sol error / Missing Interfaces

### ISSUE THREAD

**Issue by coder-tm** [smartcontractkit/documentation#330]
[https://github.com/smartcontractkit/documentation/blob/main/_includes/samples/APIRequests/ATestnetConsumer.sol](url) would not compile because of line 127 `{"mode":"full","isActive":false}`

PointerInterface.sol and ENSResolver.sol can't be found as well upon compiling.

**Comment by dmitrydao** [comment]
Thanks for catching that. Opened a PR.
