### ISSUE TITLE
https://docs.chain.link/reference results in Page Not Found (404)

### ISSUE THREAD

**Issue by 0x0I** [smartcontractkit/documentation#353]
Visiting page (link found via wiki : Node Operator Resources) results in 404. As far as I can tell, API documentation is kind of sparse so a working reference is pretty valuable.

**Comment by dwightjl** [comment]
Redirected to the main page for now. Several references exist in our docs but no single reference should be at `./reference` right now.

**Comment by 0x0I** [comment]
Hey oh ok got it and thanks for looking into it.

The "sparse" documentation comment is referencing the Node API specifically. I've only been able to find the following links (both of which seem somewhat incomplete in terms of docs for that API afaict):
- https://docs.chain.link/docs/chainlink-node-api-reference/
- https://github.com/smartcontractkit/chainlink/wiki/REST-API
