### ISSUE TITLE
Docs could use Table of Contents/"Previous Docs" Section

### ISSUE THREAD

**Issue by ritika-b** [smartcontractkit/documentation#367]
Example: get-the-latest-price-solana.md

There is a "Next Steps" section at the end of the doc, but having a section at the beginning which clearly displays the prerequisites for following the doc would be helpful to the user

**Comment by aelmanaa** [comment]
@ritika-b I cannot find `get-the-latest-price-solana.md` . Is this issue still relevant?

**Comment by ritika-b** [comment]
@aelmanaa This issue can be resolved for now. Thanks.
