### ISSUE TITLE
Add TOML variables for v2 jobs somewhere

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#382]
For example, to set the price per link on a specific job, you can set `minContractPaymentLinkJuels ` in the TOML job

**Comment by PatrickAlphaC** [comment]
https://stackoverflow.com/questions/69212408/how-to-set-job-specific-minpayment-in-v2-jobs-for-job-type-webhook/69256489#69256489

**Comment by aelmanaa** [comment]
solved by https://github.com/smartcontractkit/documentation/pull/723
