### ISSUE TITLE
Add example for list for API calls

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#430]
Add example for request.add(‘path’, ...) when JSON response is in form of an array with objects, for example

```
// Set the path to find the desired data in the API response, where the
// response format is:
// [{
//     "id": "England",
//     "odd": 5
// }]
request.add("path", "0.odd");
```

From Andrej

**Comment by andrejrakic** [comment]
Another community member had [the same issue](https://stackoverflow.com/questions/70032165/how-to-handle-json-array-response-while-using-apiconsumer).
