### ISSUE TITLE
Verify devrel node on market.link and add to documentation

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#457]
Verification is down on market.link at the moment, once it's up, we should add that information to `find an existing job` section.

**Comment by aelmanaa** [comment]
hi @PatrickAlphaC 

are you talking about the _Verified_ label?

![image](https://user-images.githubusercontent.com/4503543/155989015-0ed1ab78-f3ce-43ed-b255-730ee0511751.png)

**Comment by PatrickAlphaC** [comment]
Yep - last time I checked, no one else could verify. This might still be the case.

**Comment by aelmanaa** [comment]
market.link is not used as node explorer anymore. We list devrel nodes & jobs in [here](https://docs.chain.link/docs/decentralized-oracles-ethereum-mainnet/)
