### ISSUE TITLE
Anchor links broken with update

### ISSUE THREAD

**Issue by mccordnate** [smartcontractkit/documentation#48]
On the previous version of the documentation, I was using anchor links like this one:
https://docs.chain.link/docs/binance-smart-chain-addresses/#testnet

As you'll see, when clicking this, it doesn't jump down to the referenced section anymore

**Comment by StephenFluin** [comment]
@mccordnate Are you okay if the anchors change? We added more text to some of the titles for clarity (BSC Testnet vs testnet).

**Comment by mccordnate** [comment]
@StephenFluin For my use cases I'm okay with it. However, I heard from others that their anchor links broke as well. It would be preferable to keep as many consistent as possible so as to minimize how many pre-existing links break.
