### ISSUE TITLE
Chainlink VRF for Avalanche

### ISSUE THREAD

**Issue by krlan** [smartcontractkit/documentation#482]
Chainlink VRF Contract for Avalanche network to https://docs.chain.link/docs/vrf-contracts/, please

**Comment by gbibeaul** [comment]
Any news on this? I'm looking to get the Fuji and Avalanche coordinator address and LINK address. (I found the latter but not the coordinator address)

**Comment by ritika-b** [comment]
Hi all, VRF is not available on this network. The latest information regarding Chainlink VRF Contract addresses are on https://docs.chain.link/docs/vrf-contracts/.

**Comment by amankakar** [comment]
Hi all , Need support for VRF on Avalanche Fuji and Main net. So please guide me how I can get Chain link VRF on Avalanche Network.
