### ISSUE TITLE
[Node Operators] Fullfilling requests : ATestnetConsumer.sol constructor does not need the Link Token address anymore

### ISSUE THREAD

**Issue by elbombardi** [smartcontractkit/documentation#483]
Docs > Node Operators > Fullfilling requests 
Section : [Create a request to your node](https://docs.chain.link/docs/fulfilling-requests/#create-a-request-to-your-node)
Step : 3 

Delete "**Copy the LINK token contract address for the network you are using and paste it into the address_link field next to the Deploy button. Use one of the following network addresses**". 

Because `ATestnetConsumer.sol ` constructor does not take the LinkToken address anymore.

**Comment by dwightjl** [comment]
This is still necessary to deploy the Oracle.sol contract for now. The instruction to add the Link token contract address is not present in the section for "Create a request to your node": https://docs.chain.link/docs/fulfilling-requests/#create-a-request-to-your-node
