### ISSUE TITLE
Configuration variable $CHAINLINK_ROOT

### ISSUE THREAD

**Issue by elbombardi** [smartcontractkit/documentation#488]
In the configuration variables page, I think the variable $CHAINLINK_ROOT should be replaced by $ROOT, in this section : 
https://docs.chain.link/docs/configuration-variables/#admin_credentials_file

**Comment by dwightjl** [comment]
Thanks for calling this out. Confirmed in `schema.go`.
https://github.com/smartcontractkit/chainlink/blob/6424c2a3b3dcf15382d5093c74eb4782ffae35f9/core/config/schema.go#L21
