### ISSUE TITLE
JSON to TOML jobs for advanced-tutorial.md

### ISSUE THREAD

**Issue by ritika-b** [smartcontractkit/documentation#500]
Adding @PatrickAlphaC  feedback here:

docs/Introduction/tutorials/advanced-tutorial.md:

## 1b. Initiators
[**Initiators**](../initiators/) are what start, or initiate, a job inside an Oracle. In the case of a Request and Receive job, the [RunLog](/docs/initiators/#runlog) initiator monitors the blockchain for a request from a smart contract. Once it catches a request, it initiates the job. This runs the adapters (both core and external) that the job is configured to run eventually returning the response to the requesting contract.
 
Internal Initiators have been "sort of" replaced by "type" of jobs. And "runlog" type/initiator has is now direct request jobs. https://docs.chain.link/docs/jobs/types/direct-request/ as runlog has been deprecated.

- Could we add this context here?

## 1c. Core Adapters
 
Could we point everything to tasks instead of adapters? Maybe a callout saying that adapters are no longer supported?

https://docs.chain.link/docs/tasks/

Each oracle job has a configured set of tasks it needs to carry out when it is run. These tasks are defined by what [Adapters](../core-adapters/) they support. For example: if a job needs to make a GET request to an API, find a specific unsigned integer field in a JSON response, then submit that back to the requesting contract, it would need a job with the following Core Adapters:
- [HttpGet](../core-adapters/#httpget) - Call the API

swap these for their task counterparts

1. [HttpGet](../core-adapters/#httpget) - Calls the API and returns the body of an HTTP GET result for [ETH/USD pair](https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH&tsyms=USD).  Example:
Let's walk through a real example, where you will retrieve 24 volume of the [ETH/USD pair](https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH&tsyms=USD) from the cryptocompare API.

1. [HttpGet](../core-adapters/#httpget) calls the API and returns the body of an HTTP GET result for [ETH/USD pair](https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH&tsyms=USD).  Example:
 

- Could we use the TOML version of this?

It looks like:

```json
type = "directrequest"
schemaVersion = 1
name = "Get > Uint256"
contractAddress = "ORACLE_CONTRACT_ADDRESS"
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type=cborparse data="$(decode_log.data)"]
    fetch        [type=http method=GET url="$(decode_cbor.get)"]
    parse        [type=jsonparse path="$(decode_cbor.path)" data="$(fetch)"]
    multiply     [type=multiply input="$(parse)" times=100]     
    encode_data  [type=ethabiencode abi="(uint256 value)" data=<{ "value": $(multiply) }>]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data)"
                  data=<{"requestId": $(decode_log.requestId), "payment": $(decode_log.payment), "callbackAddress": $(decode_log.callbackAddr), "callbackFunctionId": $(decode_log.callbackFunctionId), "expiration": $(decode_log.cancelExpiration), "data": $(encode_data)}>
                 ]
    submit_tx    [type=ethtx to="ORACLE_CONTRACT_ADDRESS" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> multiply -> encode_data -> encode_tx -> submit_tx
```
externalJobID = "19747015-6833-40e7-b3fe-0fa1e76b843b"

Perhaps I'm scope creeping requesting this... Maybe it's a bigger project to update all JSON job samples to TOML.

- let me know what you think.

**Comment by aelmanaa** [comment]
solved by https://github.com/smartcontractkit/documentation/pull/669
