### ISSUE TITLE
Add more text to fulfilling-requests.md contract funding must be made in relation to LINK_DIVISIBILITY

### ISSUE THREAD

**Issue by dwightjl** [smartcontractkit/documentation#505]
From PR #497   @matthiaszimmermann

> i updated the value for ORACLE_PAYMENT for ATestnetConsumer.sol:
> 
> original code: uint256 constant private ORACLE_PAYMENT = 1 * LINK_DIVISIBILITY;
> updated code: uint256 constant private ORACLE_PAYMENT = 1 * LINK_DIVISIBILITY / 100;
>
> unsure what works better for the target audience: either add more text to he tutorial that LINK contract funding needs to be made in relation to this value or adapt ATestnetConsumer.sol and not mentioning it

Clarify this point in the docs.

**Comment by matthiaszimmermann** [comment]
ok, thx for the feedback. let me come up with a proposal for the docs

**Comment by matthiaszimmermann** [comment]
after some digging i suspect that the source for `ATestnetConsumer.sol` is located [here](https://github.com/smartcontractkit/documentation/blob/main/_includes/samples/APIRequests/ATestnetConsumer.sol), could someone confirm?

also, the fulfilling-requests tutorial is currently working with chainlink v06 contracts. looking at that it seems contract `Oracle.sol` does no longer exist with v07 contracts (replaced by Operator.sol?) and with v08 i couldn't just see what would match with the previous Oracle/Operator contracts. 

how do you guys keep the chainlink contract versionings and the documentation in sync?

**Comment by aelmanaa** [comment]
Hi @matthiaszimmermann 

thanks for your feedback and sorry for the delay.
Currently, the priority is to update all the examples and API references to match the latest version (v0.8). Moreover, All the examples must work end to end (from consumer contracts to node operators - including the callback mechanism ). 

Maybe in the future, we can consider supporting previous versions (0.7, 0.6..ETc) but this would mean maintaining parallel docs and examples for earlier versions.  But let's say the focus now is to have some consistency and working examples for v0.8 first

**Comment by aelmanaa** [comment]
We should use LINK_DIVISIBILITY in our _ANY API_ Examples to help users understand how to use it. 
Example 0,1 LINK  => (1*LINK_DIVISIBILITY)/10
