### ISSUE TITLE
Add LINK token contract address for harmony

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#509]
`0x218532a12a389a4a92fc0c5fb22901d1c19198aa`

**Comment by PatrickAlphaC** [comment]
https://explorer.harmony.one/address/0x218532a12a389a4a92fc0c5fb22901d1c19198aa

**Comment by aelmanaa** [comment]
done https://github.com/smartcontractkit/documentation/pull/553
