### ISSUE TITLE
Cannot Deploy API Consumer Contract to Mumbai Testnet

### ISSUE THREAD

**Issue by chiarawilden** [smartcontractkit/documentation#514]
**Problem**

Cannot deploy [standard API Consumer contract](https://docs.chain.link/docs/make-a-http-get-request/) for making HTTP GET requests to the Mumbai Testnet using Remix IDE and Injected Web3.

**Error Message Received** 

``` 
Gas estimation failed

Gas estimation errored with the following message (see below). The transaction execution will likely fail. 
Do you want to force sending? 
Internal JSON-RPC error. {“code”: -32000, “message”: “execution reverted”}
```

**Solutions Attempted**

Tried only 2 available Oracles for making HTTP GET Bytes32 Job:

Matrixed.Link: https://market.link/jobs/bda8ac19-8620-49f0-a771-4f2a782846f2
Link River: https://market.link/jobs/8076c7fa-fd89-4cee-bdd2-c57fa374ae7e

Tested deployment with Kovan Testnet, which was successful. 

**Contract** (With Matrixed.Link Oracle credentials)

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

import "@chainlink/contracts/src/v0.8/ChainlinkClient.sol";

/**
 * Request testnet LINK and ETH here: https://faucets.chain.link/
 * Find information on LINK Token Contracts and get the latest ETH and LINK faucets here: https://docs.chain.link/docs/link-token-contracts/
 */

/**
 * THIS IS AN EXAMPLE CONTRACT WHICH USES HARDCODED VALUES FOR CLARITY.
 * PLEASE DO NOT USE THIS CODE IN PRODUCTION.
 */
contract APIConsumer is ChainlinkClient {
    using Chainlink for Chainlink.Request;
  
    uint256 public volume;
    
    address private oracle;
    bytes32 private jobId;
    uint256 private fee;
    
    /**
     * Network: Mumbai
     * Oracle: 0x0bDDCD124709aCBf9BB3F824EbC61C87019888bb
     * Job ID: c6a006e4f4844754a6524445acde84a0
     * Fee: 0.1 LINK
     */
    constructor() {
        setPublicChainlinkToken();
        oracle = 0x0bDDCD124709aCBf9BB3F824EbC61C87019888bb;
        jobId = "c6a006e4f4844754a6524445acde84a0";
        fee = 0.1 * 10 ** 18; // (Varies by network and job)
    }
    
    /**
     * Create a Chainlink request to retrieve API response, find the target
     * data, then multiply by 1000000000000000000 (to remove decimal places from data).
     */
    function requestVolumeData() public returns (bytes32 requestId) 
    {
        Chainlink.Request memory request = buildChainlinkRequest(jobId, address(this), this.fulfill.selector);
        
        // Set the URL to perform the GET request on
        request.add("get", "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH&tsyms=USD");
        
        // Set the path to find the desired data in the API response, where the response format is:
        // {"RAW":
        //   {"ETH":
        //    {"USD":
        //     {
        //      "VOLUME24HOUR": xxx.xxx,
        //     }
        //    }
        //   }
        //  }
        request.add("path", "RAW.ETH.USD.VOLUME24HOUR");
        
        // Multiply the result by 1000000000000000000 to remove decimals
        int timesAmount = 10**18;
        request.addInt("times", timesAmount);
        
        // Sends the request
        return sendChainlinkRequestTo(oracle, request, fee);
    }
    
    /**
     * Receive the response in the form of uint256
     */ 
    function fulfill(bytes32 _requestId, uint256 _volume) public recordChainlinkFulfillment(_requestId)
    {
        volume = _volume;
    }

    // function withdrawLink() external {} - Implement a withdraw function to avoid locking your LINK in the contract
}
```

**Comment by chiarawilden** [comment]
Note – there is a typo in the contract. The fee should be 0.01 LINK, though this do not solve the issue.

**Comment by aelmanaa** [comment]
thanks @chiarawilden  and sorry for the delay. Will have a look then get back to you

**Comment by aelmanaa** [comment]
Hi @chiarawilden 

let's track the issue here: https://github.com/smartcontractkit/chainlink/issues/6300

I'm able to deploy the contract if I replace `setPublicChainlinkToken();` by `setChainlinkToken(0x326C977E6efc84E512bB9C30f76E30c160eD06FB);`

**Comment by aelmanaa** [comment]
ok as discussed in https://github.com/smartcontractkit/chainlink/issues/6300 , we will :

- replace `setPublicChainlinkToken()` by `setChainlinkToken(<link_address>)`in all our examples
- remove `setPublicChainlinkToken()` from the API reference until it is more mature

**Comment by aelmanaa** [comment]
Hello @chiarawilden ,

thanks again and I loved the way you followed up the issue in https://github.com/smartcontractkit/chainlink/issues/6300 :) would you like to contribute and give it a try?

**Comment by chiarawilden** [comment]
Yeah, give me a couple days, I'm swamped atm, but I'll give it a look! 😁

**Comment by chiarawilden** [comment]
Alrighty! So I redeployed the original contract above substituting `setChainlinkToken(<link_address>)` for `setPublicChainlinkToken()`, as you mentioned @aelmanaa. Using the Matrixed.Link job info, I was able to successfully deploy contract 0x68d9B858EB062EE10260D2302C334Eb7ab1BC504 with injected Web3. Thanks for looking into this everyone, I'm glad there's a solution, and appreciate your help!

**Comment by aelmanaa** [comment]
thank you very much @chiarawilden ! glad it worked. I'll update all the examples then ;)
