### ISSUE TITLE
Create a code sample and step-by-step guide for Utility Contracts.

### ISSUE THREAD

**Issue by dwightjl** [smartcontractkit/documentation#521]
https://github.com/smartcontractkit/documentation/blob/main/docs/chainlink-keepers/utility-contracts.md

**Comment by aelmanaa** [comment]
Hey @ritika-b 

will this PR https://github.com/smartcontractkit/documentation/pull/650 close this issue?

thanks a lot

**Comment by ritika-b** [comment]
It will not; I'll reconnect w Keepers team to see if there's an example contract they have.

**Comment by dwightjl** [comment]
https://docs.chain.link/chainlink-automation/util-overview/
https://docs.chain.link/chainlink-automation/utility-contracts
