### ISSUE TITLE
[Video Tutorial] Pegswap

### ISSUE THREAD

**Issue by fedorbcl** [smartcontractkit/documentation#530]
Build video on how to make ERC-20 token ERC-677 compatible.

https://pegswap.chain.link/

**Comment by aelmanaa** [comment]
there is a [video](https://www.youtube.com/watch?v=WKvIGkBWRUA) . i'll check if it needs to be updated

**Comment by aelmanaa** [comment]
Hello @fedorbcl 

there is actually a video which was made 1 year ago:  https://www.youtube.com/watch?v=WKvIGkBWRUA.
you can also find it [here](https://docs.chain.link/docs/link-token-contracts/#polygon-matic)
