### ISSUE TITLE
Chainlink Documentation Enhancement suggestions

### ISSUE THREAD

**Issue by sidduHERE** [smartcontractkit/documentation#537]
I recently participated in a chainlink hackathon and I faced the following issues and maybe these updates may make developer onboarding easier.

- The fee for the APIs or keepers is currently standard for each blockchain network but it may not be sufficient/subjective to gas price hikes/fluctuations. So a contract call is more likely to fail when the gas price hikes more than the standard fee(0.1 LINK on eth) and the developer/user wouldn't know whether it fails. Maybe a dynamic fee API or in-built dynamic fee update would be nice to have to increase trust in the likelihood of the contract-call success.
- Support for a local development environment that includes chainlink node/ mechanism to mock the chainlink node interactions with the smart contracts as a plugin for hardhat or truffle. It would be of great help and reduce the developer's development time by so much. If there's a dev working on it., I can contribute along with him to speed it up ? 
- Including different Error types or messages or just errors that users can get can be a good addition to the documentation as most of the time, just knowing that may help developers to solve their own issue.

Apart from them, the documentation is super good for any dev to start working on, immediately such as the remix links (which I especially liked very much ), Faucet specially built for test LINK, etc facilitates the development work so much! 

Thanks, @PatrickAlphaC  for motivating me to provide my feedback. :P

**Comment by danielgruesso** [comment]
Thanks for the feedback and sorry for the delay here @sidduHERE. There is such an adapter built by the ChaosLabs team, find it here https://github.com/ChaosLabsInc/chainlink-hardhat-plugin. Thanks for the ping @aelmanaa

**Comment by aelmanaa** [comment]
thanks so much to everyone! 
regarding the 3rd point, we are also reviewing the node operator docs: We indeed have to provide troubleshooting guides and workarounds when issues occur. 

closing this issue. feel free to reply if you have more questions
