### ISSUE TITLE
Getting a connection refused error when I try to open http://localhost:6688/ or http://127.0.0.1:6688/ on SSH tunnel (AWS EC2)

### ISSUE THREAD

**Issue by fsobh** [smartcontractkit/documentation#583]
I am hosting  a chainlink node on AWS. it works fine and everything for a few hours THEN it stops working until i redeploy a new one on EC2. I'm getting a connection refused error when I try to open http://localhost:6688/ or http://127.0.0.1:6688/ on SSH tunnel. running chainlink v.1.0.0

**Comment by dangitsdavid** [comment]
hi @fsobh, can you provide more details on your setup and the steps to replicate your issue?

Based on the error, the connection was refused from the server. I'd check if server is listening on that port during the time of the error, any changes to firewall, or simply if the Chainlink instance is still running on the instance.

**Comment by fsobh** [comment]
Yea so I followed the exact instructions of this Video using RDS, EC2, and VPC.

It seems that the moment i disconnect from my EC2 instance AFTER running `cd ~/.chainlink-rinkeby && docker run -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --env-file=.env smartcontract/chainlink:1.0.1 local n`
The Container running the node goes offline until i Re-SSH into the EC2 instance and re-run `cd ~/.chainlink-rinkeby && docker run -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --env-file=.env smartcontract/chainlink:1.0.1 local n`.

^ I verified this using netstat.

Is this a docker thing or id I not set something up right?

**Comment by fsobh** [comment]
After researching this, it seems that tools such tmux or screen will help

I changed my command from 

`cd ~/.chainlink-rinkeby &&  docker run -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --env-file=.env smartcontract/chainlink:1.0.1 local n`

to 

`cd ~/.chainlink-rinkeby && screen docker run -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --env-file=.env smartcontract/chainlink:1.0.1 local n`
