### ISSUE TITLE
Feed Registry Docs Should Include Supported Feeds

### ISSUE THREAD

**Issue by SeaAnenome** [smartcontractkit/documentation#596]
Currently the feeds registry docs page: https://docs.chain.link/docs/feed-registry does not contain a list of feeds that are supported. The feeds that are supported with the registry are not the same as the list of supported feeds for the standard method of reading a price feed.

**Comment by aelmanaa** [comment]
Thanks, @SeaAnenome for reporting.

You can find the list of feeds here:
https://docs.chain.link/docs/reference-contracts/
<img width="423" alt="image" src="https://user-images.githubusercontent.com/4503543/157231542-3d26d54d-4edd-4d0d-9cd7-1a0d352ac78c.png">

You can click then on the chain that you are interested in. For instance, here is the list for Ethereum:
https://docs.chain.link/docs/ethereum-addresses/

Does it answer your query?

**Comment by aelmanaa** [comment]
Closing this for now. Don't hesitate to re-open if you have other questions
