### ISSUE TITLE
Example of how to access Chainlink Price Feeds in Go

### ISSUE THREAD

**Issue by melchermaxwell** [smartcontractkit/documentation#644]
The docs do a great job showing how to access Chainlink Price Feeds in [Javascript](https://docs.chain.link/docs/get-the-latest-price/#javascript) and [Python](https://docs.chain.link/docs/get-the-latest-price/#python).  It would also be great to have an example in the programming language Go.

**Comment by tippi-fifestarr** [comment]
I am a relative beginner in Go, but I understand how to access Chainlink Price Feeds and would like to help the Docs.  If a Good Go Developer taught me how, I'd make a tutorial about it and work towards adding that to the Docs

**Comment by aelmanaa** [comment]
Hello @tippi-fifestarr 

thank you for the suggestion. Still interested to give it a try? You can start by having look at [go-ethereum](https://goethereumbook.org/en/). 
You can start with a simple example similar to the [javascript one](https://docs.chain.link/docs/get-the-latest-price/#javascript):

1. Instantiate an eth client
2. Instantiate a contract instance based on the eth client and the price feeds address
3. Query the contract instance for the price

don't worry, just give it a try: we'll test your code sample and review it before merging it to the main branch 😉
