### ISSUE TITLE
[Bug]: Large Response Solidity Example

### ISSUE THREAD

**Issue by loic-seguin** [smartcontractkit/documentation#688]
### Describe the bug

If we follow this link https://docs.chain.link/docs/large-responses/. The 'image_url' or 'data' are always empty after calling 'requestBytes'.

This link https://stackoverflow.com/questions/71727782/chainlink-large-responses-now-working-with-latest-docs is also related to this issue.

Everything works well on https://docs.chain.link/docs/make-a-http-get-request/ to make a simple Get Request for example.

**Comment by aelmanaa** [comment]
Hi @loic-seguin 

thank you for raising this. I'll have a look then get back to you

**Comment by loic-seguin** [comment]
Hi there, do you have any feedback about his ?

**Comment by aelmanaa** [comment]
> Hi there, do you have any feedback about his ?

Hi @loic-seguin 

we have to fix the node operator which provides the data and then update our docs accordingly. Meanwhile, can you try the example with the following config(still in Kovan):

```
  setChainlinkOracle(0x74EcC8Bdeb76F2C6760eD2dc8A46ca5e581fA656);
...
  bytes32 specId = "7da2702f37fd48e5b1b9a5715e3509b6";
```

**Comment by loic-seguin** [comment]
Hi @aelmanaa,

Thank you for your answer.

I have tried but it appears that on my contract there is no more interaction with it after the 'requestBytes'.

![image](https://user-images.githubusercontent.com/17404071/163175281-73e62739-9c5a-4560-a4ae-21c21741f7f7.png)

And in the events I have only ChainlinkRequested : 

https://kovan.etherscan.io/address/0x9b056294656c57e06d512d08f6bdfcc48c5f7e8f#events

But I should get also another event called ChainlinkRequested no ?

**Comment by aelmanaa** [comment]
hello @loic-seguin 

- please go to internal transactions to see contract-to-contract interactions and you'll see another transaction. the callback happens this way:  
oracle node(offchain) -(1)-> oracle address(onchain) -(2)-> your contract. 
- Now if you click on [events](https://kovan.etherscan.io/address/0xb37c583527f47a9781211ad77d1c37977f0e208a#events) , you'll see _chainlinkFulfilled_  . I guess you didn't see it before as it can take several minutes for data to appear in etherscan

Go back to your remixIDE and click on _data_ & _image_url_ . you should get something like this:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/4503543/163176929-877c3239-97be-4aac-9020-3dce82d9e6f9.png">

**Comment by loic-seguin** [comment]
Thx, it is working !
