### ISSUE TITLE
[Bug]: VRFConsumberBaseV2 `numWords` is a uint32 not a uint16

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#694]
### Describe the bug

In [Get a random number](https://docs.chain.link/docs/get-a-random-number/) we say that `numWords` is a `uint16` when in fact it's a `uint32`

Reference: 
[look for "uint32 numWords"](https://github.com/smartcontractkit/chainlink/search?p=1&q=%22uint32+numWords%22)
[code](https://github.com/smartcontractkit/chainlink/blob/fd91cc7346551ada741a76bac86a8563b3c679bc/contracts/src/v0.8/dev/VRFCoordinatorV2.sol#L105)

### To Reproduce

See description

### URLs

[look for "uint32 numWords"](https://github.com/smartcontractkit/chainlink/search?p=1&q=%22uint32+numWords%22)
[code](https://github.com/smartcontractkit/chainlink/blob/fd91cc7346551ada741a76bac86a8563b3c679bc/contracts/src/v0.8/dev/VRFCoordinatorV2.sol#L105)

**Comment by aelmanaa** [comment]
Thanks for the issue! will be fixed
