### ISSUE TITLE
[Bug]: Possibly broken BTT->USD oracle

### ISSUE THREAD

**Issue by 0xabhinav** [smartcontractkit/documentation#705]
### Describe the bug

Hi,

It seems the BTT->USD chainlink price oracle on ethereum is broken since aggregator is set to zero address.

To validate, check [etherscan Read Contract page for BTT->USD](https://etherscan.io/address/0x59f24f18690a2E817115D499d1159580c92De8CA#readContract).
The aggregator shows up as zero address. The values for latestRound and latestTimestamp are shown as 0, while if I query my own (and alchemy or any public) ethereum node I get an execution reversion error. 

Thanks,
Abhinav

### To Reproduce

```bash
$ curl https://rpc.ankr.com/eth -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "eth_call", "params": [{"to": "0x59f24f18690a2E817115D499d1159580c92De8CA", "data": "0x50d25bcd"}, "latest"], "id": 0}'
{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"execution reverted"}}
```

### URLs

[archive url](https://web.archive.org/web/20211102011356/https://docs.chain.link/docs/ethereum-addresses/)

### Expected behavior

A non-zero latestAnswer

**Comment by aelmanaa** [comment]
Hi @0xabhinav 

thanks for the issue. I don't find _BTT/USD_ in our [docs](https://docs.chain.link/docs/ethereum-addresses/). However, I'm able to find it via [ENS manual lookup](https://docs.chain.link/docs/ens/).
I'll investigate then get back to you

**Comment by dwightjl** [comment]
@0xabhinav Thank you for reporting this issue. This feed is not listed in the documentation and points to an aggregator at `0x0000000000000000000000000000000000000000`. See the aggregator variable on the [Etherscan](https://etherscan.io/address/0x59f24f18690a2E817115D499d1159580c92De8CA#readContract).

Live feeds are available in the [Data Feeds Lists](https://docs.chain.link/docs/ethereum-addresses/) or on [data.chain.link](https://data.chain.link/ethereum/mainnet/crypto-usd/eth-usd).
