### ISSUE TITLE
[BUG]: Improve Multivariable response page

### ISSUE THREAD

**Issue by ritika-b** [smartcontractkit/documentation#714]
### What would you like us to improve?

Add more context as to what multi-variable means; especially for new developers

### How important it is?

Based on dev feedback

**Comment by loic-seguin** [comment]
Hi,

Well the remix code doesn't work on this example.

The deployment fails on Remix with this error :

`creation of MultiWordConsumer errored: Error encoding arguments: Error: invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.5.0) (argument=null, value="", code=INVALID_ARGUMENT, version=abi/5.5.0)`

Plus I think, it is not clear enough that we are trying to request 3 different fields in one response.

I am trying to use the "Large Response" documentation to get multiple fields in the response in one REST API call. But I don't succeed to do it.

So for sure the documentation is not clear enough.

**Comment by aelmanaa** [comment]
working on it here https://github.com/smartcontractkit/documentation/issues/528
