### ISSUE TITLE
[Bug]: Broken Link

### ISSUE THREAD

**Issue by fridolinvii** [smartcontractkit/documentation#735]
### Describe the bug

The Link given has no endpoint in the documantation
https://docs.chain.link/docs/tutorials/

### To Reproduce

1. Go to 'https://market.link/data-providers/5fcd7b71-33aa-4679-bc70-75d3ebe01c04/integrations?network=1'
2. Click on '[Chainlink Tutorials](https://docs.chain.link/docs/tutorials/)'
3. See error

### URLs

- https://docs.chain.link/..
- [...](https://market.link/data-providers/5fcd7b71-33aa-4679-bc70-75d3ebe01c04/integrations?network=1)
- https://docs.chain.link/docs/tutorials/

### Expected behavior

Gives explenation how to integrate Sports Oracle

**Comment by aelmanaa** [comment]
checking with LinkPool

**Comment by aelmanaa** [comment]
@fridolinvii  thanks for raising this issue. market.link doesn't provide nodes explorer functionality anymore. I suggest that you go on [Chainlink operator-requests discord channel](https://discord.com/channels/592041321326182401/722867169813332078) and ask if a node operator is available to help you with your use case
