### ISSUE TITLE
[Bug]: LINK token addresses are no longer i

### ISSUE THREAD

**Issue by zeuslawyer** [smartcontractkit/documentation#777]
### Describe the bug

Here:  https://docs.chain.link/docs/fulfilling-requests/#deploy-your-own-oracle-contract

The three LINK token addresses are not separated by which network those addresses belong to. See screenshot.

<img width="1035" alt="Screen Shot 2022-05-27 at 11 53 20 am copy" src="https://user-images.githubusercontent.com/8016129/170612937-f97e059d-61d5-45b4-8888-e6df2eaed8a6.png">

### To Reproduce

1. Go to https://docs.chain.link/docs/fulfilling-requests/#deploy-your-own-oracle-contract
2. Click on ' (not required)
3. See error - no tabs showing for each network.
<img width="1035" alt="Screen Shot 2022-05-27 at 11 53 20 am copy" src="https://user-images.githubusercontent.com/8016129/170613031-e62f7bdc-93dc-428d-bca2-4fab8f3fe984.png">

### URLs

- https://docs.chain.link/docs/fulfilling-requests/#deploy-your-own-oracle-contract

### Expected behavior

Should show as below.

<img width="623" alt="Screen Shot 2022-05-27 at 11 55 25 am" src="https://user-images.githubusercontent.com/8016129/170613096-ab45a819-0cf7-449b-a42c-39d1b94087ed.png">

**Comment by archseer** [comment]
Looks like this was fixed? Works correctly for me on the linked page

**Comment by aelmanaa** [comment]
documentation has  changed since the issue was opened
