### ISSUE TITLE
[Enhancement]: Multi variable response with one call and multiple fields in response

### ISSUE THREAD

**Issue by loic-seguin** [smartcontractkit/documentation#779]
### What would you like us to improve?

Hi,

I have seen the updates on the documentations and it is quite nice actually ! That is a great improvement thank you.

I have tried to retrieve two fields (image and description) from a url that returns this json : 
```
{
  "description": "Description",
  "image": "ipfs://QmU45j2PKVcjEag1TJz81KEAHaOIGFcRVGvQCn7PvKg7hY1Cj/1.png"
}
```

I have tried something like the code below.

But the job that is able to do this job cannot be the same one that is used in [Multi Variable example](https://docs.chain.link/docs/multi-variable-responses/) right ?

I have to create a job that is able to retrieve several fields as a string from the same url ?

If so do I have to create a job following this https://docs.chain.link/docs/jobs/ ?

Can I create a job and submit it to a node without being force to run a node on my own ?

```
contract MultiWordConsumer is ChainlinkClient, ConfirmedOwner {
    using Chainlink for Chainlink.Request;

    bytes32 private jobId;
    uint256 private fee;

    string public image;
    string public description;

    event RequestMultipleFulfilled(bytes32 indexed requestId, bytes indexed image, bytes indexed description);

    constructor() ConfirmedOwner(msg.sender) {
        setChainlinkToken(0xa36085F69e2889c224210F603D836748e7dC0088);
        setChainlinkOracle(0x74EcC8Bdeb76F2C6760eD2dc8A46ca5e581fA656);
        jobId = '53f9755920cd451a8fe46f5087468395';
        fee = (1 * LINK_DIVISIBILITY) / 10; // 0,1 * 10**18 (Varies by network and job)
    }

    function requestMultipleParameters() public {
        Chainlink.Request memory req = buildChainlinkRequest(
            jobId,
            address(this),
            this.fulfillMultipleParameters.selector
        );
        req.add('url', 'https://...');
        req.add('pathImage', 'image');
        req.add('pathDescription', 'description');
        sendChainlinkRequest(req, fee);
    }

    function fulfillMultipleParameters(
        bytes32 requestId,
        bytes imageResponse,
        bytes descriptionResponse
    ) public recordChainlinkFulfillment(requestId) {
        emit RequestMultipleFulfilled(requestId, imageResponse, descriptionResponse);
        image = string(imageResponse);
        description = string(descriptionResponse);
    }
}
```

### How important it is?

I think any user should be able to easily retrieve any fields from a json cast at least as a string.

**Comment by loic-seguin** [comment]
Hi @aelmanaa,

Thank you for your answer !
I was testing on Kovan network.
No I haven't fixed my problem because I didn't know that I could reach a node operator to take in account my needs.
I will have to wait for the market link to be up again so that I understand how to create/give a job to a node operator.
Maybe we need a documentation to do that because here https://docs.chain.link/docs/jobs it is not explained.

Maybe it is explained on market.link.

**Comment by loic-seguin** [comment]
Just joined the discord. Thx !

**Comment by aelmanaa** [comment]
hello @loic-seguin ,

just saw that a node operator answered you on Discord. Going to close this issue, please feel free to reply if you need more assistance from our end.
FYI, there is an issue to improve "find existing jobs" : https://github.com/smartcontractkit/documentation/issues/713 . We will work on it once https://market.link is up with the new release
