### ISSUE TITLE
Env var docs are very out of date

### ISSUE THREAD

**Issue by samsondav** [smartcontractkit/documentation#80]
Docs here are very out of date: https://docs.chain.link/docs/configuration-variables/

We need to go over them and update to be in line with what's in `config.go`. I can help with this, feel free to reach out.

**Comment by dmitrydao** [comment]
Can you send url to `config.go` if it is in the public repo? If not, I'll ping you.

**Comment by dmitrydao** [comment]
@samsondav Is this still the case?
