### ISSUE TITLE
[Bug]: Importing a Keystore Documentation is Outdated (wrong)

### ISSUE THREAD

**Issue by SeaAnenome** [smartcontractkit/documentation#820]
### Describe the bug

https://docs.chain.link/docs/miscellaneous/#importing-a-keystore shows that the command to import a keystore is "chainlink local import ./keystore.json" 

However, the command is now: 

chainlink keys eth import --oldpassword oldpasswordcredsfile keystore.json

 

### To Reproduce

1. Connect to CL node docker container and run command listed in docs
2. Get back (my keystore file is call privatekey.json): 
root@ce929a0bff50:/chainlink# chainlink local import privatekey.json
2022-06-23T17:57:51.000Z [DEBUG] Initializing API credentials                       cmd/client.go:636       file=/chainlink/apicredentials
No help topic for 'import'
root@ce929a0bff50:/chainlink#

### URLs

https://docs.chain.link/docs/miscellaneous/#importing-a-keystore

### Expected behavior

root@ce929a0bff50:/chainlink# chainlink keys eth import --oldpassword apicredentials privatekey.json
2022-06-23T18:00:13.563Z [DEBUG] Initializing API credentials                       cmd/client.go:636       file=/chainlink/apicredentials
parseResponse error: Error; key with ID 0x345aF178A3D894815EEC819A4E0b7C68E2584468 already exists

except instead of the key already exsting, it would import 🤷 (this has been tested by a customer)

**Comment by aelmanaa** [comment]
Hi @SeaAnenome 

sorry for the delay and many thanks for reporting the issue.
