### ISSUE TITLE
[Enhancement]: add links for IaC solutions

### ISSUE THREAD

**Issue by RomanS-re** [smartcontractkit/documentation#859]
### What would you like us to improve?

We suggest reviewing IaC solutions reference in your documentation here: https://docs.chain.link/docs/best-security-practices/#infrastructure-as-code-iac 

- add link to Terraform module for [serverless Chainlink OCR node on AWS](https://github.com/ChainOrion/terraform-aws-chainlink-node)
- add link to Terraform module for [serverless Chainlink External Adapters on AWS](https://github.com/ChainOrion/terraform-aws-chainlink-ea)
- review [SDL Chainlink Kubernetes Deployment](https://github.com/securedatalinks/ChainlinkKubernetes) link. Seems it's unavailable

### How important it is?

It could be helpful for new node operators or existing operators not taking an IaC. With those modules, it's possible to create highly available, fault-tolerant, and scalable serverless infrastructure on AWS for both Chainlink OCR node and Chainlink External Adapters.

Used by Orion operator on Eth mainnet and reviewed by Mycelium and Chorus operators.

**Comment by aelmanaa** [comment]
Thank you very much @RomanS-re. just fixed the 3rd point

**Comment by RomanS-re** [comment]
Hi @aelmanaa, any update on when #860 could be merged? Is there anything from my side that I need to add or change?

**Comment by aelmanaa** [comment]
Hello @RomanS-re 

just realized that I made a typo. Will fix it.
