### ISSUE TITLE
[Enhancement]: Move starter kits location based on ecosystem

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#887]
### What would you like us to improve?

I'd love to see the starter kits moved based on their ecosystem.

1. Have a "Starter Kits" page under the main getting started location under "resources".
<img width="234" alt="Screen Shot 2022-08-01 at 5 21 29 PM" src="https://user-images.githubusercontent.com/54278053/182248819-d463b08d-b986-49b7-b79a-da537d1324d9.png">

This page would have all the starter kits, and maybe a reference to this github repo: 
https://github.com/smartcontractkit/starter-kits

(Or, it would have a reference to EVM starter kits and Solana Starter Kits)

2. Have the EVM chains and Solana chains pages have references to the starter kits. 
<img width="285" alt="Screen Shot 2022-08-01 at 5 22 29 PM" src="https://user-images.githubusercontent.com/54278053/182248951-b3061583-7bae-48f7-a286-8f60d07dfa71.png">

right now, the EVM Chains has one under "Install frameworks" but it's not often updated. Wondering if it would be easier to point to this repo: https://github.com/smartcontractkit/starter-kits and just put them in EVM vs Solana categories somehow.

### How important it is?

Low priority

**Comment by dwightjl** [comment]
We reorganized our top nav and made some updates to the "Install Frameworks" page: https://docs.chain.link/resources/create-a-chainlinked-project?parent=gettingStarted

I think that resolves this issue. We match the starter kits list 1-1 now.
