### ISSUE TITLE
[Bug]: Broken 'API Reference' Link

### ISSUE THREAD

**Issue by web5223** [smartcontractkit/documentation#923]
### Describe the bug

Broken link on https://chain.link/developer-resources

### To Reproduce

1. Go to https://chain.link/developer-resources
2. Click on 'API Reference' link under the 'API External Calls' section
3. See error - Page 404

### URLs

https://chain.link/developer-resources

### Expected behavior

The embedded URL is 'https://docs.chain.link/docs/chainlink-vrf-api-reference?_ga=2.138733939.1942086690.1660243204-1803446209.1660243204' which leads to the 404 error.  However, pasting 'https://docs.chain.link/docs' into the browser works fine.

**Comment by dwightjl** [comment]
URL redirects are fixed but the links on https://chain.link/developer-resources could still use some improvements. Leaving this open for now.
