### ISSUE TITLE
Add a "what is Chainlink" section & new engineer button

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#95]
Intuition: Right now, when I go to the documentation of something someone tells me to checkout, the first thing I want to do is ask "where the hell am I?"

We should have some form of navigation to do so.

Additionally, on our landing page, we have 3 action items. https://docs.chain.link/
None of them are beginner-friendly. I'd like to test out adding a "New engineer? Start here" type button that will take them to our tutorials.

**Comment by PatrickAlphaC** [comment]
Have text at the top of the page that says "what is chainlink", and a quick blurb at the top. 
- Check on the status of the "what is chainlink video", and possibly link there and to any supporting information.

Potentially add a button at the top for "Brand new to solidty? -> Go here"
Add a Text for "Experienced with solidity? Use one of the buttons below"

**Comment by dmitrydao** [comment]
Where should we refer people if they are new to Solidity?
