### ISSUE TITLE
[Enhancement]: <Operator.sol as reccomended default not Oracle.sol>

### ISSUE THREAD

**Issue by jonahkaye** [smartcontractkit/documentation#958]
### What would you like us to improve?

I was using Oracle.sol when trying to set up customized jobs for a test chainlink node, but all transactions between the node and oracle contract were failing. I switched to Operator.sol and they started to work. I think the chainlink dev docs say to use Oracle.sol and have a walkthrough for using that, so would you be able to change the walkthrough to direct Node Operators to use Operator.sol?  https://docs.chain.link/docs/fulfilling-requests/

### How important it is?

Oracle.sol shouldn't be the directed default if it isn't actually the reccomended contract to use, so I think pretty important in terms of helping devs get node setup and operation right the first time.

**Comment by aelmanaa** [comment]
Hello @jonahkaye 

thank you very much for your input. Yes, I agree with you. the whole [page](https://docs.chain.link/docs/fulfilling-requests/) must be reviewed and we will indeed recommend Operator.sol

**Comment by aelmanaa** [comment]
Fixed https://github.com/smartcontractkit/documentation/pull/1097
