### ISSUE TITLE
[Bug]: API Large Responses Example is not working on Goerli

### ISSUE THREAD

**Issue by danicuki** [smartcontractkit/documentation#965]
### Describe the bug

I tried to run [this example](https://docs.chain.link/docs/any-api/get-request/examples/large-responses/) exactly as described. But it is not working.

### To Reproduce

1. Open the [contract in Remix](https://remix.ethereum.org/#url=https://docs.chain.link/samples/APIRequests/GenericBigWord.sol).
2. Compile and deploy the contract using the Injected Provider environment. 
3. Fund your contract with 0.5 LINK. 
4. Call the data and image_url functions to confirm that the data and image_url state variables are not set.
5. Run the requestBytes function. 
6. After few seconds, call the data and image_url functions. You should get non-empty responses, BUT, **responses are always empty**, even after calling the requestBytes function many times.

### URLs

https://docs.chain.link/docs/any-api/get-request/examples/large-responses/

### Expected behavior

You should get non-empty responses, BUT, **responses are always empty**, even after calling the requestBytes function many times

**Comment by aelmanaa** [comment]
Hi @danicuki 

thanks for reporting the issue. Having a look then will get back to you

**Comment by aelmanaa** [comment]
Hi @danicuki ,

can you check again? you can re-open the issue if it still occurs

**Comment by danicuki** [comment]
It is still with the same wrong behavior. Do I need to change anything in my contract?

**Comment by danicuki** [comment]
here is the transaction that is not working properly https://goerli.etherscan.io/tx/0x0aa65513c1c149e55a28fc0c08298c578bdf9a43c2e2a64b2b4860fe0001ee47

**Comment by aelmanaa** [comment]
@danicuki what is not working exactly?

From what I see ,the callback was made (cf. transaction: https://goerli.etherscan.io/tx/0x02d700daed32220d0bc263e096843dd836224b6f6602eb44c9f9a2eed6c1c10c)

I also checked interacting with your contract(5546f9DFAD6641E3fD36c53a3D9a86a1cd8e9ba7) on Remix IDE and I see that image_url and data are populated

<img width="689" alt="image" src="https://user-images.githubusercontent.com/4503543/187221203-ca2737a7-41cc-4444-81f7-b1940f144356.png">

**Comment by danicuki** [comment]
I don't understand, because on my side it does not return the string and data:

![Screen Shot 2022-08-29 at 12 21 05](https://user-images.githubusercontent.com/77552/187236108-877ec030-f565-4ee0-815b-2d308cb5d9a8.png)

**Comment by danicuki** [comment]
I don't know the reason why, but I just disconnected and reconnected my wallet and it worked. It seems that Remix has an issue with cache...

**Comment by aelmanaa** [comment]
@danicuki happy you found out the root cause.
