### ISSUE TITLE
Migrate "banner" examples to rinkeby or goerli

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#97]
Kovan has been having issues in the past, and it would be ideal to migrate our "banner" examples to rinkeby or goerli.

Looking for votes for rinkeby or goerli.

Rinkeby is used by projects like opensea, while goerli is the stomping grounds for ETH 2

**Comment by PatrickAlphaC** [comment]
Rinkeby Votes

**Comment by PatrickAlphaC** [comment]
Goerli Votes

**Comment by dmitrydao** [comment]
I think Kovan we're keeping Kovan for now, right? If yes, let's close the issues

**Comment by PatrickAlphaC** [comment]
Let's close it, but use it to vote on which testnet we want to switch to. It should be kept as "needs votes"
