### ISSUE TITLE
[Enhancement]: Users mis-interpret minimum spend requirement on Keepers

### ISSUE THREAD

**Issue by wentzeld** [smartcontractkit/documentation#971]
### What would you like us to improve?

Users are misinterpreting the minimum spend requirement. They are reading that it is per transaction, when it is in fact per upkeep. Need to ensure this is crystal clear.

### How important it is?

This is scale of 1 to 2 on a range of 1 = High, 5 = Low

**Comment by ritika-b** [comment]
Resolved
