### ISSUE TITLE
Checksum all addresses

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#98]
Right now, addresses are not checksummed, and a lot of compilers will throw errors if they are just copy pasted as so. For example:

The [LINK token address of Rinkeby](https://docs.chain.link/docs/vrf-contracts/#rinkeby) is marked as:
`0x01be23585060835e02b77ef475b0cc51aa1e0709` 
And it should be:
`0x01BE23585060835E02B77ef475b0Cc51aA1e0709`

**Comment by dmitrydao** [comment]
Is there a single place where we can find checksums?
