### ISSUE TITLE
[Bug]: <Broken link>

### ISSUE THREAD

**Issue by jbusta21** [smartcontractkit/documentation#991]
### Describe the bug

https://docs.chain.link/docs/vrf-contracts/v1/#polygon-matic-mumbai-testnet

link that is broken

### To Reproduce

3. See error

### URLs

- https://docs.chain.link/..
- ...
https://docs.chain.link/docs/vrf-contracts/v1/#polygon-matic-mumbai-testnet

**Comment by aelmanaa** [comment]
Hello @jbusta21 

the correct URL is:  https://docs.chain.link/docs/vrf/v1/supported-networks/#polygon-matic-mumbai-testnet

but please note that vrf-v1 is deprecated. Here is the link to [vrf v2](https://docs.chain.link/docs/vrf/v2/introduction/) for reference
